### ISSUE TITLE
No node known to accept io.motown.domain.api.chargingstation.CreateChargingStationCommand

### ISSUE THREAD

**Issue by soyoeml** [motown-io/motown#60]
Hi, 

I have already tested simple project. Now I use samples-configuration-distributed to try:
1. configured rabbitmq based on document.
2. run mvn jetty:run on each folder in folder samples-configuration-distributed, excluding root folder.
3. connect ws://localhost:8083/socket CS001 by OCPP 1.5 client.
4. send boot notification:
[2,"tMGpP5fvHakFnZnfUio6D3bSniUvj7Zv","BootNotification",{"chargePointVendor":"MOTOWN","chargePointModel":"MODEL1","chargePointSerialNumber":"gir.vat.mx.000e48","chargeBoxSerialNumber":"gir.vat.mx.000e48","firmwareVersion":"1.0.49","iccid":"","imsi":"","meterType":"DBT NQC-ACDC","meterSerialNumber":"gir.vat.mx.000e48"}]

I got this response: 
[3,"JH464ojDhJhUFiir3yQlqeZZtx34lZ85",{"status":"Rejected","currentTime":"2017-04-03T23:07:56Z","heartbeatInterval":900}]

I debugged the code and found it threw a message:
**org.axonframework.commandhandling.distributed.CommandDispatchException: An error occurred while trying to dispatch a command on the DistributedCommandBus: No node known to accept io.motown.domain.api.chargingstation.CreateChargingStationCommand**

What is missing?

Thanks
-soyoeml

**Comment by soyoeml** [comment]
I found this issue. It's because the jgroups doesn't support IPv6. If you set JVM to disable the IPv6( -Djava.net.preferIPv4Stack=true ) , you will not see this message.

**Comment by dennislaumen** [comment]
Hi @soyoeml! I'm assuming you're running macOS? If I remember correctly Java on macOS runs on IPv6 by default (other OSes don't).

**Comment by soyoeml** [comment]
Hi Dennis, where can I get the CIR username and password or where to register one?

**Comment by dennislaumen** [comment]
Hi @soyoeml, CIR is used for roaming with charge cards in the Netherlands. As far as I'm aware there is no public site to register but the CIR system is in the process of being phased out anyway. One of the replacements is [OCPI](http://www.nklnederland.nl/projecten/onze-lopende-projecten/ocpi-open-charge-point-interface/) (a protocol) which is used by, among others, [e-clearing](http://e-clearing.net).
