### ISSUE TITLE
Hibarnate 4.3 and later with JPA 2.1 specs

### ISSUE THREAD

**Issue by haukurk** [motown-io/motown#62]
Has anyone managed to use Hibarnate 4.3+ (using the JPA 2.1 specs) with this project on Tomcat?

**Comment by markvandenbergh** [comment]
We have not yet tried that Hibernate version yet. Have you tried it? Did it work? If not: what issues did you run into?

**Comment by markvandenbergh** [comment]
Fixed in 92209588433a54de3d76cab89fa256c6e77ced5d
